### ISSUE TITLE
Additional function for the plugin: focuser

### ISSUE THREAD

**Issue by llogical** [ThornyFFXI/MiscAshita4#1]
Please concider adding an additional function that may select or exempt any giving polID or alpha window. This could be very helpful when dealing with multiple windows and only bringing non-idling characters to the front. Thanks

**Comment by ThornyFFXI** [comment]
The focuser plugin has been converted to an addon to allow users more customization, and this feature has been added.  It's new permanent home is here:
https://github.com/ThornyFFXI/Focuser/
